[language-server.zk]
command = "zk"
args = ["lsp"]


[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown"]
roots = [".zk"]
language-servers = ["zk"]
